### ISSUE TITLE
Feature: Support tags for escalation policies, teams, users, etc

### ISSUE THREAD

**Issue by tim-rival** [PagerDuty/terraform-provider-pagerduty#144]
The tagging feature in PagerDuty is quite nice for quickly finding the right user or escalation policy to reassign an incident. Any plans to support adding / updating tags on the relevant PD resources?

**Comment by djsly** [comment]
also looking for tags.

**Comment by chipm73** [comment]
Still looking for tags.

**Comment by jaronoff97** [comment]
Bump on this, any updates?

**Comment by stmcallister** [comment]
Wanted to drop a note in here. I've been working with the team responsible for the Tags endpoints of the API in order to add resources for Tags and  Tag Assignments to the provider. It appears that they are reworking the API endpoints at the moment and recommended I hold off on adding the resources to the provider for now. Will update this thread as I know more.

**Comment by kkom** [comment]
Hey @stmcallister, thanks for the update back in December! Do you happen to know anything more now? :)

**Comment by brenwhyte** [comment]
Also looking at this, as I KNOW folks are going to ask for it. Even an eta would be great. Thanks guys.

**Comment by bohdanborovskyi-ma** [comment]
Hey @stmcallister could you be so kind and notify if there any update about tags resources support in TF provider?
Currently we are forced to exucute a shell scripts via local-exec provisioners mechanism, which is not very convenient and robust method.

**Comment by stmcallister** [comment]
I'll be sure to update this thread when I hear more about when the public API endpoints for Tags will be ready to support the Terraform provider. 😄 No news yet.

**Comment by rockyluke** [comment]
Hello, sorry to ask again 🙏 do you have some news about tags support ?

Thanks !

**Comment by ryanking** [comment]
What's wrong with implementing this with the current api and changing when there is a new one?

**Comment by rockyluke** [comment]
Tags are now supported in the provider, see the documentation :

- https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/tag
- https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/tag_assignment

**Comment by imjaroiswebdev** [comment]
I'll proceed to close this issue since this feature was already added as @rockyluke highlighted
