### ISSUE TITLE
Unexpected terraform plan on provider version 1.3.1

### ISSUE THREAD

**Issue by vietstuff** [PagerDuty/terraform-provider-pagerduty#147]
### Background
Terraform v0.12.5
PagerDuty Provider Version: 1.3.1
Unexpected terraform plan behaviour stops after we lock pagerduty provider version to 1.3.0

### Affected Resource(s)
- pagerduty_user
- pagerduty_team_membership

### Expected Behavior
Changes should not be made for users if nothing has changed

### Actual Behavior
Terraform proposes to remove user from team
```
# module.user_name.pagerduty_user.first_responder will be updated in-place
  ~ resource "pagerduty_user" "first_responder" {
        avatar_url      = "https://secure.gravatar.com/avatar/1111"
        color           = "teal"
        description     = "Managed by Terraform"
        email           = "helloworld@hello.co.nz"
        id              = "123456"
        invitation_sent = false
        job_title       = "Software Engineer"
        name            = "Hello World"
        role            = "limited_user"
      ~ teams           = [
          - "123456",
        ]
        time_zone       = "Pacific/Auckland"
    }
```

It then propose to add back the user to the team after applying the above changes
```
# pagerduty_team_membership.team_product_domain_audience_network_carmen_liu will be created
  + resource "pagerduty_team_membership" "team_membership" {
      + id      = (known after apply)
      + team_id = "123456"
      + user_id = "848484"
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Update pagerduty provider to 1.3.1
2. Create a pagerduty user in your terraform then run the apply
3. After applying successfully, try to perform terraform plan and you should see the plan similar to the example above (terraform tries to remove user from team or add them back to the team after removing them). The unexpected terraform plan behaviour still persists after terraform apply

**Comment by stmcallister** [comment]
Hello! Just cleaning up old issues. It appears this one was resolved thanks to #146. Please repost if I'm mistaken. Thanks!
