### ISSUE TITLE
Incorrect attribute value type after upgrading to Terraform 0.12

### ISSUE THREAD

**Issue by Edeholland** [PagerDuty/terraform-provider-pagerduty#156]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.8
+ provider.pagerduty v1.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_schedule

### Terraform Configuration Files
```hcl
resource "pagerduty_schedule" "office-hours" {
  name      = "Allez platform office-hours schedule"
  time_zone = "Europe/Amsterdam"

  layer {
    name                         = "Layer 1"
    start                        = "2019-01-28T00:00:00+01:00"
    rotation_virtual_start       = "2019-01-28T00:00:00+01:00"
    rotation_turn_length_seconds = 86400
    users                        = ["${module.user1.pagerduty_id}", "${module.user2.pagerduty_id}", "${module.user3.pagerduty_id}"]

    restriction {
      type              = "weekly_restriction"
      start_day_of_week = 1
      start_time_of_day = "00:00:00"
      duration_seconds  = 432000
    }
  }
}
```

### Expected Behavior
Terraform configuration should be valid.

### Actual Behavior
```hcl
Error: Incorrect attribute value type

  on pagerduty.tf line 10, in resource "pagerduty_schedule" "office-hours":
  10:     users                        = ["${module.user1.pagerduty_id}", "${module.user2.pagerduty_id}", "${module.user3.pagerduty_id}"]

Inappropriate value for attribute "users": element 0: string required.
```

### Important Factoids
I tried changing the syntax according to the Terraform 0.12 upgrade. This resulted in the following code:
```hcl
    users                        = ["module.user1.pagerduty_id, module.user2.pagerduty_id, module.user3.pagerduty_id"]
```
That resulted in the following plan:
```hcl
- "P4NL2MI",
- "PJOQBN0",
- "PX6GLNZ",
+ "module.user1.pagerduty_id, module.user2.pagerduty_id, module.user3.pagerduty_id",
```
and the following error:
```hcl
Error: PUT API call to https://api.pagerduty.com/schedules/PZRN12K failed 400 Bad Request. Code: 2001, Errors: [User id must be a valid ID.], Message: Invalid Input Provided

  on pagerduty.tf line 1, in resource "pagerduty_schedule" "office-hours":
   1: resource "pagerduty_schedule" "office-hours" {
```
It seems like it's correctly identifying the strings, but now it's taken the literal text instead of the value from the module. I am wondering what the correct syntax is in Terraform 0.12 to be able to reach the Pagerduty API with the correct values.

**Comment by Edeholland** [comment]
I solved the issue using the `flatten` function like this:
```hcl
users                        = flatten([module.user1.pagerduty_id, module.user2.pagerduty_id, module.user3.pagerduty_id])
```
I still don't understand why that fixed the problem. Does `module.user1.pagerduty_id` return a list?

**Comment by chenrui333** [comment]
I created a similar issue on this, https://github.com/terraform-providers/terraform-provider-pagerduty/issues/222

**Comment by stmcallister** [comment]
It appears that this issue was resolved, so I'm going to close it. Please repost if I'm mistaken.
