### ISSUE TITLE
Error: Get https://api.pagerduty.com/abilities: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by eigo-s** [PagerDuty/terraform-provider-pagerduty#161]
### Terraform Version
```
$ terraform version
Terraform v0.12.10
+ provider.pagerduty v1.4.0
```

### Affected Resource(s)
- pagerduty_user

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 0.12.10"
  backend "local" {
    path = "./terraform.tfstate"
  }
}

provider "pagerduty" {
  version = "~> 1.4.0"

  token = "${var.pagerduty_token}"
}

data "pagerduty_user" "me" {
  email = "eigo_suzuki@dwango.co.jp"
}
```

### Debug Output
- https://gist.github.com/eigo-s/100c6ada7a19e67c8950ee3d4725053e

### Expected Behavior
Get data source and get user information

### Actual Behavior
Using the same token and executing curl succeeds, so token seems to be no problem
- https://gist.github.com/eigo-s/3a893705c8e52f66a62e784e99bc7b9f

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids

Executed on mac book.
Running the same code on the server rarely succeeds, but fails almost as well.

**Comment by stmcallister** [comment]
Hello! Sorry for taking so long to get to this issue. Are you still experiencing this? I can't seem to reproduce with the current version of the provider.

**Comment by stmcallister** [comment]
Going to close the issue. Please repost if you continue to experience this issue.
