### ISSUE TITLE
data source pagerduty_vendor not handling special characters properly

### ISSUE THREAD

**Issue by NicoleYson** [PagerDuty/terraform-provider-pagerduty#171]
### Terraform Version
```
Terraform v0.12.18
+ provider.pagerduty v1.4.1
```

### Affected Resource(s)
- `data.pagerduty_vendor`

### Terraform Configuration Files
```hcl
data "pagerduty_vendor" "sentry" {
  name = "Sentry (Legacy)"
}
```

### Expected Behavior
What should have happened?
the [`vendor.Name`](https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/pagerduty/data_source_pagerduty_vendor.go#L54) should have matched the `vendor.id`: `PKG4M95` when the data source's attribute `name` was set to `Sentry (Legacy)` 
```json
{
  "vendor": {
    "id": "PKG4M95",
    "type": "vendor",
    "summary": "Sentry (Legacy)",
    "self": "https://api.pagerduty.com/vendors/PKG4M95",
    "html_url": null,
    "name": "Sentry (Legacy)",
    "website_url": "https://getsentry.com/welcome/",
    "long_name": "Sentry (Legacy)",
    "logo_url": "https://s3.amazonaws.com/pdpartner/sentry_large.png",
    "thumbnail_url": "https://s3.amazonaws.com/pdpartner/sentry_thumb.png",
    "description": "Sentry provides real-time crash reporting for your web apps, mobile apps, and games.",
    "integration_guide_url": "https://www.pagerduty.com/docs/guides/sentry-integration-guide/",
    "connectable": false,
    "generic_service_type": "api",
    "alert_creation_default": "create_alerts_and_incidents",
    "alert_creation_editable": true,
    "is_pd_cef": false,
    "developer_name": "",
    "support_portal": "",
    "support_email": "",
    "documentation_url": ""
  }
``` 

### Actual Behavior
|Config   |Behavior   |
|---|---|
|![image](https://user-images.githubusercontent.com/14220781/70869911-7e91ac00-1f42-11ea-9e7d-22d1b92481e3.png)| ❌ `Error: Unable to locate any vendor with the name: Sentry (Legacy)`|
|![image](https://user-images.githubusercontent.com/14220781/70869983-17c0c280-1f43-11ea-8d65-f64052caa77c.png)| ❌`Error: rpc error: code = Unavailable desc = transport is closing` |
|![image](https://user-images.githubusercontent.com/14220781/70871060-e995af80-1f4f-11ea-900e-d097341d7e74.png)| :x: `Error: Unable to locate any vendor with the name: sentry (legacy)` |
|![image](https://user-images.githubusercontent.com/14220781/70870182-ec3ed780-1f44-11ea-9ced-597ebd8473b6.png)| ❌`vendor = "PKAPG94"` - Which makes sense. |
|![image](https://user-images.githubusercontent.com/14220781/70869922-99642080-1f42-11ea-8f4e-f864f158f631.png)| ✅`vendor = "PKG4M95"` |
|![image](https://user-images.githubusercontent.com/14220781/70869860-e4c9ff00-1f41-11ea-80de-f60262f0b9d4.png)| ✅`vendor = "PKG4M95"`  |

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```sh
cat <<EOF >> "pd-provider-issue-171.tf"
data "pagerduty_vendor" "sentry" {
  name = "Sentry (Legacy)"
}

output "testy" {
  value = data.pagerduty_vendor.sentry.id
}

EOF
```
`terraform apply`

### Important Factoids
- Running in circleci
     - `image: circleci/golang:1.13`
- This is for a module that creates github repositories and associated resources 
    - Interacts with the pagerduty, sentry, github providers
    - Likely the consequence of a recent change as it now wants to force recreate a couple hundred resources 🤣 
```hcl
-/+ resource "pagerduty_service_integration" "sentry" {
      ...
      ~ vendor            = "PKG4M95" -> "PKAPG94" # forces replacement
    }
```

### References
Where it may have gone awry:
- Issue: https://github.com/terraform-providers/terraform-provider-pagerduty/issues/165 
    - PR attempting to close the issue: https://github.com/terraform-providers/terraform-provider-pagerduty/pull/166 

Instead of opening an issue, I was actually going to PR the "fix" myself, but I did not want to impose. Specifically, because I see this going two ways and it's probably best for the maintainers to choose. I don't want to impose just to fix my specific use case. 

Additionally, I would double-check whether or not the unit tests are working properly [here](https://github.com/terraform-providers/terraform-provider-pagerduty/blob/25a10c2fef8428a717e8b1924a2ab560dd9feea7/pagerduty/data_source_pagerduty_vendor_test.go#L45-L79). I tried to deliberately break it, and I'm not certain whether or not it's actually running. 

Here's a go playground link to show the [regexp.MustCompile Issue](https://play.golang.org/p/eFdzqI_TjCY) that I'm seeing. 
and here's where I see the issue in the provider: 
https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/pagerduty/data_source_pagerduty_vendor.go#L53-L69
It looks like`strings.EqualFold` isn't returning a match, so it continues to `regexp.MustCompile`?

**Comment by stmcallister** [comment]
It appears this issue is resolved, as I'm unable to reproduce. Please repost if this is still a problem.
