### ISSUE TITLE
Unable to create extension of type "event_transformer_api_inbound_integration"

### ISSUE THREAD

**Issue by p3rshin** [PagerDuty/terraform-provider-pagerduty#173]
### Terraform Version
terraform v0.12.18

### Affected Resource(s)
Unable to create extension with type "event_transformer_api_inbound_integration" (Custom Event Transformers) 

### Terraform Configuration Files
```
resource "pagerduty_service_integration" "cet" {
name = “Custom Event Transformers”
service = "${pagerduty_service.example.id}"
type = "event_transformer_api_inbound_integration"
}
```

### Debug Output
There are no errors during "plan", but "apply" errors with:
```
pagerduty_service_integration.cet: POST API call to https://api.pagerduty.com/services/P60A2U4/integrations failed 400 Bad Request. Code: 2001, Errors: [Vendor can't be blank], Message: Invalid Input Provided”
```
if "vendor" is specified  “plan” stage fails with:
```
Error: pagerduty_service_integration.cet: "type": conflicts with vendor
Error: pagerduty_service_integration.cet: "vendor": conflicts with type
```

### Expected Behavior
Extension gets created

### Actual Behavior
It is not possible to create an extension of type `event_transformer_api_inbound_integration` using Terraform

### References
Based on https://www.terraform.io/docs/providers/pagerduty/r/service_integration.html "vendor" is optional.

**Comment by stmcallister** [comment]
I've learned that vendor and type have an either/or relationship, and you want to default to using vendor. Every vendor integration (that I've found) saves the type as `event_transformer_api_inbound_integration`. So, rather than setting the type, I'd recommend setting vendor.

**Comment by jfcantu** [comment]
> I've learned that vendor and type have an either/or relationship, and you want to default to using vendor. Every vendor integration (that I've found) saves the type as `event_transformer_api_inbound_integration`. So, rather than setting the type, I'd recommend setting vendor.

The Terraform documentation isn't very clear on this, but that's probably because the PagerDuty documentation isn't either. They both say that `type` may be `event_transformer_api_inbound_integration`, and that `vendor` is an optional field - which strongly suggests that this is the correct way to create an event transformer.

(As far as I can tell, the only way to discover that "Custom Event Transformer" exists as a vendor, is to stumble across it in the list returned from querying `/vendors`.)

Ref:

https://www.terraform.io/docs/providers/pagerduty/r/service_integration.html
https://api-reference.pagerduty.com/#!/Services/post_services_id_integrations

**Comment by p3rshin** [comment]
thanks @jfcantu @stmcallister that seems to have worked, but it is unclear how to pass the config... am I right that it will not be possible? as mentioned on https://github.com/PagerDuty/go-pagerduty/issues/67

**Comment by stmcallister** [comment]
The config that @jfcantu posted is the correct way to set up a Custom Event Transformer service integration through Terraform. To see the available vendor types you do need to make a call to the `/vendors` API endpoint. This can actually be done inside the PagerDuty API docs. Go to [GET /vendors](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1vendors/get) and click on the "Try It" tab. Clicking the Send button in that tab will give you a list of vendors. 

Apologies on taking so long to respond. Please repost if you have any further issues.
