### ISSUE TITLE
terraform resources updates not happen in order

### ISSUE THREAD

**Issue by chenrui333** [PagerDuty/terraform-provider-pagerduty#212]
terraform 0.12.24
pagerduty provider v1.5.1

I have an escalation_policy referencing one schedule, and that schedule have a user (the user moved from one team to another) in it.

While I was updating all the changes in three sources all in one, but the execution seems not happening in order, which causing API deletion error like this:

```
Error: DELETE API call to https://api.pagerduty.com/teams/PEH9O6E/users/PIB3HGM failed 400 Bad Request. Code: 2001, Errors: [User cannot be removed as they belong to an escalation policy on this team], Message: Invalid Input Provided
```

My question is how to enforce the resource update order? We ended up making one change at a time.

**Comment by chenrui333** [comment]
cc @stmcallister, wonder if you can take a look on this.

**Comment by stmcallister** [comment]
Hey @chenrui333! Sorry for the delay. Have you tried using the `depends_on` field? It's a meta-argument available in Terraform that allows you to set dependencies. It may be able to help you keep those resource dependencies inline.

https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies

Let me know if that doesn't help.

**Comment by stmcallister** [comment]
It looks like PR #258 fixed this issue. Going to close. Please repost is this issue persists.

**Comment by chenrui333** [comment]
Thanks @stmcallister!
