### ISSUE TITLE
[schedule] update schedule rotation

### ISSUE THREAD

**Issue by chenrui333** [PagerDuty/terraform-provider-pagerduty#215]
terraform version 0.12.24
pagerduty provider 1.5.1

I wonder whenever the schedule got updated (i.e. schedule has one person removed), is the schedule object got recreated? If that is the case, it is quite disruptive for my team (as who is on call before and is on call again). Thanks!

**Comment by stmcallister** [comment]
I'm not seeing this behavior. When I add users to my schedule layer the same schedule object is only updated, not deleted and created. Can you share a little more about what changes you're trying to make?

**Comment by stmcallister** [comment]
haven't heard back on this in a while. going to close. please repost if this is still an issue.

**Comment by chenrui333** [comment]
@stmcallister I actually still have this issue when updating the schedules (i.e. adding/deleting users in the same schedule).

Is there any best practice to keep the schedule the same when adding/removing user from the schedule? Thanks!
