### ISSUE TITLE
Manually removed resources break terraform workflow

### ISSUE THREAD

**Issue by mahsoud** [PagerDuty/terraform-provider-pagerduty#230]
### Terraform Version
Terraform v0.12.24
+ provider.pagerduty v1.7.1

### Affected Resource(s)
pagerduty_ruleset_rule

### Steps to Reproduce
1. Create a configuration file with pagerduty_ruleset_rule resource
2. Apply configuration via 'terraform apply'
3. Login to pagerduty website, and manually remove the rule created
4. Attempt to generate plan / reapply configuration

### Expected Behavior
Configuration drift should be detected, the rule should be re-created

### Actual Behavior
404 error from API call while refreshing resources state breaks terraforms workflow

**Comment by stmcallister** [comment]
Thanks for bringing this up. I have tested and have been able to reproduce the error. i'll work on a fix.

**Comment by ryankt** [comment]
This also happens (404) if you change the "ruleset" parameter on an existing pagerduty_ruleset_rule resource.

ie: during a plan, terraform tries to query the ruleset rule id under the new ruleset id - but errors out with a 404.

Or would this be a separate issue?

**Comment by jwlusby** [comment]
I am also struggling with this issue (404 and TF failure) when pagertduty_ruleset or pagerduty_ruleset_rules resources are removed.
This requires TF state manipulation to remove the missing resources from the TF state.

**Comment by maristgeek** [comment]
Affects pagerduty_service_event_rule as well, and probably generically anything the provider gets a 404 for.

**Comment by AstritCepele** [comment]
Any idea when this will be fixed? 
```
│ Error: GET API call to https://api.eu.pagerduty.com/service_dependencies/technical_services/PWZZP50 failed 404 Not Found. Code: 404, Errors: [], Message: Service Not Found
│ 
│   with pagerduty_service_dependency.dependencies 
```

**Comment by elin-mdsol** [comment]
This affects `pagerduty_team` resource as well.  But so far doesn't affect `pagerduty_team_membership`, `pagerduty_escalation_policy` and `pagerduty_service` in my testing.

**Comment by gsreynolds** [comment]
Rules are being deprecated and replaced
