### ISSUE TITLE
pagerduty_ruleset_rule - Position "null" Creates a Change During next Run

### ISSUE THREAD

**Issue by christopherbox** [PagerDuty/terraform-provider-pagerduty#234]
The position variable is not flagged as required. When omitting the position field it applies fine. However the next time the run is called, it will pull the position value which provokes Terraform to perform a "change" to change the position value that was set back to "null". This doesn't actually negatively harm things, but the plans will never be clean.

### Terraform Version
v0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_ruleset_rule

### Terraform Configuration Files
```esource "pagerduty_ruleset_rule" "rules" {
  for_each = local.ruleset_rules

  ruleset = local.ruleset_id
#   position = each.value.position
  disabled = "false"

  conditions {
    operator = "and"
    subconditions {
      operator = "equals"
      parameter {
        value = each.key
        path = "details.severity"
      }
    }
    subconditions {
      operator = "contains"
      parameter {
        value = var.service_name
        path = "details.service"
      }
    }
  }
  actions {
    route {
      value = var.service_id
    }
    severity  {
      value = each.value.pagerduty_severity
    }
    annotate {
      value = "Managed by terraform"
    }
    extractions {
      target = "dedup_key"
      source = "details.id"
      regex = "(.*)"
    }
    extractions {
      target = "description"
      source = "description"
      regex = "(.*)"
    }
    priority {
      value = each.value.priority_value
    }
  }
}
```

### Expected Behavior
The data pulled should omit the "null" value if set and not compare.

### Actual Behavior
```
module.service_activation.module.pagerduty_ruleset_rule.rules["Average"] will be updated in-place
~ resource "pagerduty_ruleset_rule" "rules" {
        disabled = false
      - position = 9 -> null
...
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Create a ruleset_rule without a position value`
2. `Apply the plan`
3. `Re-plan or re-apply the Terraform plan`

**Comment by stmcallister** [comment]
Thanks for bringing this up, and that's a good suggestion! I'll see what can be done about this.

**Comment by matt-canty-dragon** [comment]
@christopherbox has there been any detriment to having this set to `null` for the time-being or did you switch to trying to determine a value for each.

I just switched from a value I set back to `null`. Wondering if I should revert or just leave it and wait for fix.

**Comment by christopherbox** [comment]
The only detriment is that the plan is never clean. So we have to read a longer and longer plan the more services we add into our terraform configs. We basically have a for_each loop that goes through the services and applies event rules based on the service name and organizes them to their associated PagerDuty services.

The Rulesets are not all organized by one play as the services themselves are found amoung multiple teams. So we don't need a value for each of them, but we need rules there to dictate the flow of alerts and priorities of the alerts based on the receiving monitoring service sending them.

**Comment by matt-canty-dragon** [comment]
Yeah we have a similar setup. In the end I ran all the rulesets in order in a separate file to create consistent position. But even that is broken now. 

`null` support is the right thing here.

**Comment by foxylion** [comment]
I also see this. We are trying to create rule sets in different modules. So it is impossible to have a global knowledge which `position` we should set. It would be awesome if we could just leave it empty.

**Comment by foxylion** [comment]
For everyone that needs a fix for the always pending changes when using `position = null`. It is possible to tell Terraform to ignore some of the changes that are detected.

```
data "pagerduty_ruleset" "my_ruleset" { name = "My Ruleset" }

resource "pagerduty_ruleset_rule" "some_rule" {
  ruleset  = pagerduty_ruleset.my_ruleset
  actions {
    route { value = "..."" }
  }
  lifecycle {
    ignore_changes = [position]
  }
}
```

**Comment by christopherbox** [comment]
You are amazing @foxylion! That works! Thats a very easy workaround.

**Comment by skmsurf** [comment]
Thanks @foxylion that really helped me out and got me past the annoying list of state changes that do not need to show up.  For me with hundreds of ruleset_rule resources it really adds up!

**Comment by jylauril** [comment]
Sadly the ignore_changes workaround doesn't work anymore in newer terraform and it's really dirtying up our plans for no good reason.

We maintain a fairly large amount of services which each registers several rules to an environment specific ruleset. Changes are always done for one service at a time and which ever service is being updated re-positions itself in the ruleset due to how this resource works and creates a lot of unnecessary noise for our plans.

I really wish we could create service specific rulesets in our infra, but the way the routing key is per ruleset, it makes it a giant pain to set up for each integration when you're dealing with close to a hundred different services.

I really hope they will address this issue soon. Just give us another value, like `position = -1` to indicate that as long as the rule is in the ruleset the position doesn't matter and shouldn't change. 🙏
