### ISSUE TITLE
pagerduty_service_dependency: does not support update

### ISSUE THREAD

**Issue by mhyzon** [PagerDuty/terraform-provider-pagerduty#236]
It looks like the PD API doesn't support updating for the `pagerduty_service_dependency` resource.  Probably have to destroy & recreate instead.

### Terraform Version
```
$ terraform -v
Terraform v0.12.23
+ provider.pagerduty v1.7.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_service_dependency

### Debug Output

(I've obfuscated the IDs & names)

```
# module.business_services.pagerduty_service_dependency.technical_service_dependancy["XXXXX"] will be updated in-place
  ~ resource "pagerduty_service_dependency" "technical_service_dependancy" {
        id = "XXXXXXXXXXXXXX"

      ~ dependency {
            dependent_service {
                id   = "XXXXXXX"
                type = "business_service"
            }

          ~ supporting_service {
              ~ id   = "ABCDEF1" -> "ABCDEF2"
                type = "service"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

...

Error: doesn't support update

  on ../../../modules/pagerduty/business_services/main.tf line 31, in resource "pagerduty_service_dependency" "technical_service_dependancy":
  31: resource "pagerduty_service_dependency" "technical_service_dependancy" {
```

### Expected Behavior
Assuming that Pagerduty API will not support an update on this object any time soon, terraform should destroy/create the resource.

### Actual Behavior
`Error: doesn't support update`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Change configuration so an existing pagerduty_service_dependency resource has a different supporting service
1.  `terraform apply`

**Comment by mhyzon** [comment]
There might be an edge case here where the service dependency was removed on the PagerDuty side, but not removed from state (perhaps when the supporting service was removed? I might have done that manually.)

Playing around with the PD API directly, it was saying it couldn't find the service when I tried to dissociate manually. I removed it from state manually and new resource got created fine.

**Comment by stmcallister** [comment]
Hi @mhyzon, yes, the underlying API for `service_dependencies` does not support updating. So, to make changes you'll need to destroy the dependency in your Terraform state and then create a new `service_dependency` resource. I've added a note to the `service_dependency` docs to help clarify this. Thanks for pointing out this wasn't clear!

**Comment by 0x91** [comment]
@stmcallister it sounds like the resource needs to have the `ForceNew` schema attribute: https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#forcenew

**Comment by TomTucka** [comment]
I can pick this up and make sure that the schema for `pagerduty_service_dependency` has `ForceNew` set to `True`

**Comment by msuterski** [comment]
Is there any update on this? We just run into it while using the resource within a custom module and it's difficult to destroy and then create in an automated pipeline.

**Comment by stmcallister** [comment]
closing, as #271 appears to have addressed this.
