### ISSUE TITLE
[Feature request] Response Play resource

### ISSUE THREAD

**Issue by mahsoud** [PagerDuty/terraform-provider-pagerduty#254]
Proposed Resource:
pagerduty_response_play

Why:
It would be nice to manage Response plays via terraform manifest files.

**Comment by stmcallister** [comment]
Agreed!  Support for Response Plays is currently in the works!

**Comment by alexjurkiewicz** [comment]
Is this still in-progress?

**Comment by sheldonhull** [comment]
My use case is ensuring a predefined subscriber list of stakeholders is available for a newly created team via PagerDuty. I added my +1, but wanted to mention this so more detail is brought on this request. Cheers

**Comment by stmcallister** [comment]
Hello! PR #278 should have addressed this. It's available in version 1.8.0 or later of the provider. 

Going to close this issue. Please create another issue if you have any issues with the new resource.
