### ISSUE TITLE
PUT API call to schedule failed 500 Internal Server Error.

### ISSUE THREAD

**Issue by maheshwarirohit87** [PagerDuty/terraform-provider-pagerduty#263]
Hello,

We are using a pagerduty provider to create the team, users, Schedules, Escalation Policy, Services, etc. When we create all the resources for the first time everything works fine but when we try to update the schedule or any other component and run apply we are getting the below error

**Error: PUT API call to https://api.pagerduty.com/schedules/xxxx failed 500 Internal Server Error. Code: 2000, Errors: <nil>, Message: An internal error has occurred. PagerDuty administrators have been notified.**

I had a call and some working sessions with Pagerduty support under the support ticket 271583. But still, we were not able to fix the issue. This is very intermittent. If I run the terraform apply 3 times it shows the issue with the different schedule every time.

I don't think we are sending the API calls more than the limit but we are still getting this error.

Let me know if you need more details.

### Terraform Version
Terraform v0.12.29

### Affected Resource(s)
Pageduty Schedule

**Comment by stmcallister** [comment]
Thank you for posting this! This was addressed with #264 and published in v1.7.10. Thanks!
