### ISSUE TITLE
New Pause / Suspend feature that has recently come out for rulesets is missing from Terraform.

### ISSUE THREAD

**Issue by DaveMullin** [PagerDuty/terraform-provider-pagerduty#272]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.26
+ provider.pagerduty v1.7.10

### Affected Resource(s)

pagerduty_ruleset_rule

### Terraform Configuration Files

  actions {
    route {
      value = data.pagerduty_service.technical_service.id
    }
    severity  {
      value = "warning"
    }
    annotate {
      value = "From Terraform"
    }
    priority {
      value = "AAAAAAAA"
    }
    suspend {
      value = var.pageduty_pause_seconds
    }

#OUTPUT
Error: Unsupported block type

  on modules/moduleA/dave.tf line 154, in resource "pagerduty_ruleset_rule" "ao_apmservice_ruleset_rule_error_pause":
 154:     suspend {

Blocks of type "suspend" are not expected here.

### Expected Behavior
What should have happened?

### Actual Behavior

Suspend added to ruleset

### Steps to Reproduce
terraform apply`

### Extra

 It appears to be present in the api just not in terraform

https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1rulesets~1%7Bid%7D~1rules/post
https://support.pagerduty.com/docs/rulesets#paused-incident-notifications
https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/ruleset_rule
https://github.com/heimweh/go-pagerduty/blob/master/pagerduty/ruleset.go

**Comment by stmcallister** [comment]
This should now be available in the current version of the provider...that would be v1.9.3, as of this writing. Going to close. Please open another issue if you experience any further issues.
