### ISSUE TITLE
Output IDs for pagerduty_schedule not recognised when in for_each

### ISSUE THREAD

**Issue by samuelbaena** [PagerDuty/terraform-provider-pagerduty#277]
### Terraform Version
v0.13.4

### Affected Resource(s)
- pagerduty_schedule

### Terraform Configuration Files
```hcl
provider "pagerduty" {
  token = xxxxx
}

variable "schedules" {
  default = [
    {
      name  = "Test1"
      start = "2020-11-02T10:00:00-00:00"
      users = ["Pxxxxx"]
    },
    {
      name  = "Test2"
      start = "2020-11-02T10:00:00-00:00"
      users = ["Pxxxxx"]
    }
  ]
}

resource "pagerduty_schedule" "schedules" {
  for_each = { for schedule in var.schedules : schedule.name => schedule }

  name        = each.value.name
  description = "${each.value.name} default schedule. Managed by Terraform"
  time_zone   = "Europe/Madrid"
  layer {
    start                        = each.value.start
    rotation_virtual_start       = each.value.start
    rotation_turn_length_seconds = 604800
    users                        = each.value.users
  }
}

output "schedule_ids" {
  value = pagerduty_schedule.schedules[*].id
}

terraform {
  required_providers {
    pagerduty = {
      source = "pagerduty/pagerduty"
    }
  }
  required_version = ">= 0.13"
}

```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Shown outputs of resources/will know after apply

### Actual Behavior
```hcl
Error: Unsupported attribute

  on main.tf line 37, in output "schedule_ids":
  37:   value = pagerduty_schedule.schedules[*].id

This object does not have an attribute named "id".
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### Important Factoids
N/A

**Comment by TechIsCool** [comment]
```hcl
output "schedule_ids" {
  value = pagerduty_schedule.schedules[*].id
}
```
Can be written as
```hcl
output "schedule_ids" {
  value = [ for k, v in  var.schedules : pagerduty_schedule.schedules[k].id ]
}
```

**Comment by samuelbaena** [comment]
> ```terraform
> output "schedule_ids" {
>   value = pagerduty_schedule.schedules[*].id
> }
> ```
> 
> Can be written as
> 
> ```terraform
> output "schedule_ids" {
>   value = [ for k, v in pagerduty_schedule.schedules : v.id ]
> }
> ```

Already tried al variations of it, same result I'm afraid

**Comment by samuelbaena** [comment]
Got it to work with:
`[for w in pagerduty_schedule.schedules[*] : values(w)[*]["id"]]`

Will close the issue, although it would be nice to make it work in an easier way.
