### ISSUE TITLE
Support Service Event Rules resource

### ISSUE THREAD

**Issue by tdmalone** [PagerDuty/terraform-provider-pagerduty#279]
Re-creating this issue (was formerly #202) as support is now available in the PagerDuty API.

Relevant comments from the previous issue:

> Global Rulesets and Global Event Rules (legacy) are resources supported through the provider, but Service Event Rules are not yet supported.
> 
> [See the documentation on PagerDuty Rulesets](https://support.pagerduty.com/docs/rulesets).

> Thanks for the request! Unfortunately, Service Level Event Rules are not supported by the PagerDuty API. Once it is, we'll probably add it to the `ruleset` and `ruleset_rule` resources.

> early-access support is now available https://developer.pagerduty.com/api-reference/docs/CHANGELOG.md#2020-09-16

**Comment by enieuw** [comment]
I'd be interested in this as well as right now our only option is to craft and send the JSON payloads to the Pagerduty API via TF.

I took a quick peek a the API docs but judging by the API endpoint it makes more sense for me to have this either under the `service` resource or via a separate resource `service_event_rule` as the rules are always mapped to a specific service. I have no problem doing the implementation but would like to confirm that my line of thinking is in line with what the maintainers have in mind for this API.

**Comment by stmcallister** [comment]
Thank you @enieuw!! Similar to how there is a separate resource for `pagerduty_team_membership` I think it would make the most sense from a usability perspective to have a separate `service_event_rule` resource.

This was on my radar, but if you have bandwidth right now, you might be able to get it out faster than I would. I do know that @robertstettner had [begun work on adding Service Event Rules](https://github.com/heimweh/go-pagerduty/pull/46) to the Go library the provider uses to connect to the PagerDuty API. I'm not sure where he's at on that. I'll ping him on that thread and see.

**Comment by edobry** [comment]
Hello, just chiming in to say I'm also interested in this functionality and willing to contribute, if there is an opportunity to do so. If someone else is already working on this I don't want to get in the way, however.

**Comment by betabandido** [comment]
@edobry FYI, the required work in the Go library seems to be finished: https://github.com/heimweh/go-pagerduty/pull/46

**Comment by stmcallister** [comment]
Yep, I'm currently working on getting this added to the provider. Should be added soon. 🤞
