### ISSUE TITLE
[Bug] Unable to update account owner with general full access API key

### ISSUE THREAD

**Issue by Sudoblark** [PagerDuty/terraform-provider-pagerduty#291]
### Terraform Version
```bash
xxxx@xxxx PagerDuty % tfenv list
  0.14.4
* 0.12.20 (set by /usr/local/Cellar/tfenv/2.0.0/version)
  0.11.14
```

### Affected Resource(s)
- pagerduty_user

Only impacts users who, in the PagerDuty GUI, are listed as having the "Account Owner" role.

### Terraform Configuration Files
I've created a dummy version of the same config below:

- users.json (in prod, is encrypted with git-crypt because of data like email etc)
```json
{

    "Example_User" : {
        "name" : "Example User",
        "description" : "User account, managed by Terrraform",
        "email" : "hello@world",
        "job title" : "Dummy user",
        "role" : "owner",
        "colour" : "red"
    }
}
```
- users.tf
```hcl
locals {
    # Read in local
    users = jsondecode(file("${path.module}/users.json"))
}

resource "pagerduty_user" "users" {
    for_each = local.users
    name  = each.value["name"]
    email = each.value["email"]
    description = each.value["description"]
    job_title = each.value["job title"]
    role = each.value["role"]
    color = each.value["colour"]
}
```

### Debug Output
Note, I've just trimmed it down to the bits relating to the resources in question and removed sensitive content

[Gist Link](https://gist.github.com/Sudoblark/19086015bf792617a283da317d51db3b)

### Panic Output
Terraform did not panic

### Expected Behaviour
On a Terraform apply, the user should have been updated appropriately as:
- Config logic in Terraform is OK
- Import of existing resource happened without issue
- API key used on the PagerDuty end has full access (tested both general access and user keys)
- Headers in log output indicate Terraform is using correct API key and PagerDuty RESTAPI V2

### Actual Behaviour
In addition to the log output already linked, Terraform produces the following errors:
```bash
pagerduty_user.users["xxxx"]: Modifying... [id=xxxx]

Error: PUT API call to https://api.pagerduty.com/users/xxxx failed 403 Forbidden. Code: 2010, Errors: <nil>, Message: Access Denied

  on users.tf line 6, in resource "pagerduty_user" "users":
   6: resource "pagerduty_user" "users" {

```

- Mirroring the same query in postman, with the same API keys and headers, returns the same error:

![image](https://user-images.githubusercontent.com/28766101/105180647-c0682b00-5b22-11eb-90a3-df1038406135.png)

### Steps to Reproduce
1. `terraform apply`

Or

1. Mirror query in postman/curl etc

### Important Factoids
- PagerDuty API key used is listed as having full access under add-ons > API Access
- Given this also doesn't work in postman, this is probably an API issue requiring either the API or docs ( [API](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1users~1%7Bid%7D/put) , [Key generation](https://support.pagerduty.com/docs/generating-api-keys#section-generating-a-general-access-rest-api-key) , [Terraform](https://www.pagerduty.com/eng/how-why-terraform/) ) to be updated
- As such this probably needs to be raised as an issue against the API itself (unless my troubleshooting is wrong in which case apologies!) but i was unable to find such a repo against the org other than [api-schema](https://github.com/PagerDuty/api-schema)
- 
### References
- NA

**Comment by treksler** [comment]
I am seeing the same thing.
I have posted to the pagerduty support forum here
https://community.pagerduty.com/forum/t/unable-to-edit-account-owner-via-api-or-terraform/2297

**Comment by stmcallister** [comment]
Hello! As mentioned in the original issue comment and in the [thread on the community ](https://community.pagerduty.com/forum/t/unable-to-edit-account-owner-via-api-or-terraform/2297) posted by @treksler, this is an issue with the PagerDuty API and not the provider in particular. Also mentioned in the Community thread this feedback has been passed on to the appropriate. Going to close this issue for now.

**Comment by jmehnle** [comment]
I would argue that the provider should offer a way to not include the `role` attribute in the `PUT` request. I can determine that the role is `owner` easily enough, but I have no way to prevent it from being set on the owner user.
