### ISSUE TITLE
Missing "token" argument after upgrade to 0.13

### ISSUE THREAD

**Issue by ocdrums3** [PagerDuty/terraform-provider-pagerduty#294]
### Terraform Version
0.13.6

### Debug Output
https://gist.github.com/ocdrums3/cd28138b45a8f7e61e49fd5faa36ce9b.js

### Expected Behavior
terraform plan without any errors

### Actual Behavior
Receiving error `The argument "token" is required, but was not set`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform validate`

### Important Factoids
Started receiving this error after upgrading terraform from 0.12.29 to 0.13.6 and initializing the backend

**Comment by skmsurf** [comment]
I remember running into this same "token" not set error when upgrading Terraform versions recently, and believe it was related to the Terraform registry changing the Pagerduty provider path.  I would edit your versions.tf with the updated source path for the Pagerduty provier, terraform init and try again.

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    pagerduty = {
      source = "PagerDuty/pagerduty"
      version = "1.8.0"
    }
  }
  required_version = ">= 0.13"
}

```

**Comment by ocdrums3** [comment]
Unfortunately that is not the issue. That's actually what I have set, which was created by the terraform upgrade command

**Comment by skmsurf** [comment]
What about the pagerduty api key is it set properly in main.tf?


```
variable "pagerduty_token" {
}

# Configure the PagerDuty provider
provider "pagerduty" {
  token = var.pagerduty_token
}
```

**Comment by ocdrums3** [comment]
While nothing was changed with that api key, the issue does seem to revolve around that. The token is a variable which is read from a encrypted yaml file which is decrypted using sops:

```
data "sops_file" "pd_secrets" {
  source_file = "../secrets.yaml"
}

provider "pagerduty" {
  token   = data.sops_file.pd_secrets.data["pd_api_key"]
  version = "1.8.0"
}
```

**Comment by ocdrums3** [comment]
> I remember running into this same "token" not set error when upgrading Terraform versions recently, and believe it was related to the Terraform registry changing the Pagerduty provider path. I would edit your versions.tf with the updated source path for the Pagerduty provier, terraform init and try again.
> 
> ```
> terraform {
>   required_providers {
>     aws = {
>       source = "hashicorp/aws"
>     }
>     pagerduty = {
>       source = "PagerDuty/pagerduty"
>       version = "1.8.0"
>     }
>   }
>   required_version = ">= 0.13"
> }
> ```

This actually was the solution. I have no idea what I was looking at yesterday but after revisiting this again this morning I realized I did not have it configured as you suggested. After updating the error went away. Thank you!

**Comment by edobry** [comment]
I'm experiencing this exact issue, and I've confirmed that I'm using the correct provider path. Is there any known workaround?

**Comment by ocdrums3** [comment]
To provide more info, the provider was being set in two different locations in my setup. In the folder where the module was and in the folder where I was referencing the module, and I had only updated it in one place. Make sure you don't have the old provider specified somewhere else in your project

**Comment by edobry** [comment]
Appreciate the response; I checked all over but this doesn't seem to by my issue, thanks anyway!
