### ISSUE TITLE
[Tracking] Provider compiled for darwin/arm64

### ISSUE THREAD

**Issue by skyzyx** [PagerDuty/terraform-provider-pagerduty#297]
### Important Factoids

Apple M1 chip is here. Porting work is occurring for everyone. Opening a tracking ticket to provide public visibility on the work.

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

* https://github.com/golang/go/issues/38485
* https://github.com/hashicorp/terraform/issues/27257
* https://github.com/hashicorp/terraform-provider-aws/issues/16948

**Comment by skyzyx** [comment]
**Status update:** Go 1.16 was released today with [non-prerelease, first-class support for `darwin/arm64`](https://golang.org/doc/go1.16#darwin).

**Comment by jontonsoup** [comment]
So is there any progress here?
