### ISSUE TITLE
Error importing pagerduty_response_play

### ISSUE THREAD

**Issue by troytoman** [PagerDuty/terraform-provider-pagerduty#298]
I am unable to import a pagerduty_response_play and receive the following error:

`Error: Error importing pagerduty_response_play. Expecting an importation ID formed as '<response_play_id>.<from_email>'`

Here is the import command I have run:

`terraform import pagerduty_response_play.test-resonse <response-play-id>`

I am running this on terraform 13.4 and the provider 1.8.0

Possibly related, I notice that attempting to do a GET operation on this response play in API is also getting this error:

`"You must provide a valid email address in the 'From' header to perform this action."`

I am investigating that as well.

**Comment by troytoman** [comment]
My bad on this one. The PagerDuty documentation is missing the required "from" field. They are committed to fix that omission. I now see that can be included on the import command line. Closing this one out.

**Comment by ProfMoo** [comment]
@troytoman I am currently trying to import response plays as well, and am confused by this error message. My response plays in the PagerDuty UI don't have an email associated with them. How did you find the e-mail?

**Comment by troytoman** [comment]
I found that my own email worked. I think it just needs to be a valid email from the account.
