### ISSUE TITLE
routing_keys is still not returned by the pagerduty_ruleset data source

### ISSUE THREAD

**Issue by DoctorPolski** [PagerDuty/terraform-provider-pagerduty#307]
### Terraform Version
0.14.7

### Affected Resource(s)
- `pagerduty_ruleset`

### Expected Behavior
`pagerduty_ruleset` data source should contain `routing_keys`

### Actual Behavior
Despite the recent update the ruleset data source still does not return `routing_keys`.

### Steps to Reproduce
1. terraform plan
2. "This object does not have an attribute named "routing_keys"."

### References
PR: https://github.com/PagerDuty/terraform-provider-pagerduty/pull/305

### Discussion
The function requires the `routing_keys` schema to be added in order for it to return them:

```
func dataSourcePagerDutyRuleset() *schema.Resource {
	return &schema.Resource{
		Read: dataSourcePagerDutyRulesetRead,

		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
			},
		},
	}
}
```

should be:

```
func dataSourcePagerDutyRuleset() *schema.Resource {
	return &schema.Resource{
		Read: dataSourcePagerDutyRulesetRead,

		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
			},
			"routing_keys": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
		},
	}
}
```

When compiled and used locally the above works.

I originally requested this functionality last week directly via the PagerDuty helpdesk. I would be happy to submit this as a PR if given the required repo permissions.

Many thanks :)

**Comment by stmcallister** [comment]
Thanks for submitting the PR!

**Comment by stmcallister** [comment]
Going to close this issue. Please reopen if the issue still persists.
