### ISSUE TITLE
Random error when deploying rule inside a ruleset

### ISSUE THREAD

**Issue by bmx0r** [PagerDuty/terraform-provider-pagerduty#315]
### Terraform Version
Terraform v0.12.21
pagerduty provider : v1.9.3

### Affected Resource(s)
Please list the resources as a list, for example:
- ruleset_rule

### Terraform Configuration Files
we use a module to encapsulate so maybe better to dump from the state
```hcl
terraform state show module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule
# module.ER_xxxxx_ruleset_name.pagerduty_ruleset_rule.ruleset_rule: (tainted)
resource "pagerduty_ruleset_rule" "ruleset_rule" {
disabled = false
id = "a5f0911f-ace6-496b-a42f-970d02a94629"
position = 0
ruleset = "4e2aa7d4-cc96-4b93-9ee4-a554d837b4c6"

actions {
annotate {
value = "From prod environment"
}

priority {
value = "XXXXX"
}

route {
value = "ZZZZZZ"
}

severity {
value = "info"
}
}

conditions {
operator = "or"

subconditions {
operator = "equals"

parameter {
path = "payload.custom_details.team"
value = "squad-above"
}
}
}
}
```

### Debug Output
```
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [20s elapsed]
module.ER_ogone_ruleset_direct-htp_catchall.pagerduty_ruleset_rule.ruleset_rule: Still modifying... [id=350df132-10a8-4055-ad0e-8a06af693378, 20s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [30s elapsed]
module.ER_ogone_ruleset_direct-htp_catchall.pagerduty_ruleset_rule.ruleset_rule: Still modifying... [id=350df132-10a8-4055-ad0e-8a06af693378, 30s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [40s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [50s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [1m0s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [1m10s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [1m20s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [1m30s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [1m40s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [1m50s elapsed]
module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule: Still creating... [2m0s elapsed]
Error: GET API call to https://api.pagerduty.com/rulesets/4e2aa7d4-cc96-4b93-9ee4-a554d837b4c6/rules/a5f0911f-ace6-496b-a42f-970d02a94629 failed 404 Not Found. Code: 0, Errors: <nil>, Message: Rule Not Found
on /builds/global/terraform/environments/ogone/alerting/.terraform-prod-alerting/modules/ER_ogone_ruleset_direct-htp_above/main.tf line 41, in resource "pagerduty_ruleset_rule" "ruleset_rule":
41: resource "pagerduty_ruleset_rule" "ruleset_rule" {
Error: Error updating ruleset rule 350df132-10a8-4055-ad0e-8a06af693378 position 0 needs to be 1
on /builds/global/terraform/environments/ogone/alerting/.terraform-prod-alerting/modules/ER_ogone_ruleset_direct-htp_catchall/main.tf line 41, in resource "pagerduty_ruleset_rule" "ruleset_rule":
41: resource "pagerduty_ruleset_rule" "ruleset_rule" {

from what I get here the api never answer when creating module.ER_xxxxx_ruleset_name-name.pagerduty_ruleset_rule.ruleset_rule but we can see that TF receive somehow the ID of the new rule: a5f0911f-ace6-496b-a42f-970d02a94629
but it doesnt exist...

this job is playing with a lot of ressources:
Terraform summary:
"pagerduty_service_dependency": {
"create": 53,
"delete": 53
},
"pagerduty_business_service": {
"update": 1
}


```

### Expected Behavior
the ressource should exist and/or the state shouldnt be updated if not created

### Actual Behavior
state knows the new rule, but it doesnt exist in PAgerduty

### Steps to Reproduce
It happends randomly, so no real procedure here

### Important Factoids
the TF code is playing a lot with datasource, could it be some rate limit from the API? Still this shoould be taken smoothly by the provider

**Comment by stmcallister** [comment]
If I'm following you correctly, you are querying for an event rule with a datasource. How soon are you querying for the rule after it's created?

**Comment by bmx0r** [comment]
Hi,
I'm not sure I get the question :) you are assuming I do a get of a ruleset_rule but there is no datasource to do so, so I dont see how in our code we can trigger this query.
In the log we can see that TF is looping until the ressource is created, until a timeout of 2m `Still creating... [2m0s elapsed`
So it confirms that i'm not getting the ressource, but I'm just creating it

After the error i went to the webUI with the following url:
https://xxxxx.pagerduty.com/rules/rulesets/4e2aa7d4-cc96-4b93-9ee4-a554d837b4c6
and the rule was not there

I hope my answer helps :)

**Comment by bmx0r** [comment]
Also maybe worth mentioning, that I clean up the state, and apply again and it worked, which again point me in the direction where the provider react strangely maybe because of an unexpected answer from the api?

**Comment by stmcallister** [comment]
Ah, okay. So, you're creating the `ruleset_rule` but the provider gets hung up on the creation of the rule. The provider seems to think it's created the rule because it has an ID. However, there is no rule in PagerDuty with the new ID. Do I have that right?

**Comment by bmx0r** [comment]
exactly :)

**Comment by christopherbox** [comment]
I as well have ran into the issue with this resource. When you create an event rule in the ruleset and the position that you set does not match the position that gets returned, it errors.

This happens when your position value is higher than what currently exists.

For example, if you have **5** event rules in the ruleset, and you create a new one with position **10**, it will return a position of **6**. It seems to be specifically this output.

`Error: Error updating ruleset rule 350df132-10a8-4055-ad0e-8a06af693378 position 0 needs to be 1`

The worst part is that it keeps on trying until it times out like @bmx0r's debug output.

**Comment by mrwacky42** [comment]
Is this the same as #397, just presenting differently?

**Comment by gsreynolds** [comment]
Rules are being deprecated and replaced
