### ISSUE TITLE
`pagerduty_team` should return a list of members

### ISSUE THREAD

**Issue by TomTucka** [PagerDuty/terraform-provider-pagerduty#345]
Heya,

The `pagerduty_team` data source should be able to return a list of team members, I've added an example use case below! 

### Affected Resource(s)
- pagerduty_team (d)

### Terraform Configuration Files
```hcl
data "pagerduty_team" "my_team" {
  name = "My Team Name"
}

resource "pagerduty_schedule" "my_schedule" {
  name      = "My Schedule"
  time_zone = "Europe/London"

  layer {
    name                         = "Layer 1"
    rotation_turn_length_seconds = 604800
    rotation_virtual_start       = "2019-08-19T09:00:00+01:00"
    start                        = "2019-07-26T12:15:46+01:00"
    users                        = data.pagerduty_team.my_team.members
  }
}


```
### Expected Behavior
`pagerduty_team` should return a list of members

### References
- https://github.com/heimweh/go-pagerduty/blob/master/pagerduty/team.go#L146

**Comment by imjaroiswebdev** [comment]
Hi @TomTucka to solve this request We have added the new `users` **data source** for querying the list of users from the PagerDuty account, which allows to filter by one or more teams at the same time. This new **data source** will be available with our next release of the provider.
