### ISSUE TITLE
Slack v2 next generation support

### ISSUE THREAD

**Issue by jbfavre** [PagerDuty/terraform-provider-pagerduty#365]
Hi there,

Now that Slack v2 next generation is in early access (https://support.pagerduty.com/docs/slack-v2-next-generation), I wonder when it'll be supported by Terraform provider.
As far as I understood, it'll make Terraform much easier to manage: the authentication is only need once at workspace level.
Connexions from team or services to Slack channel will reuse it which could allow to fully declare it through Terraform.

Do you have any plan to support Slack v2 next generation integration ?

**Comment by stmcallister** [comment]
I believe #381 addressed this issue. Going to close. Please reopen if it's not the case.
