### ISSUE TITLE
Pagerduty ruleset rules positions are not guaranteed on apply and require multiple applies to get no drift.

### ISSUE THREAD

**Issue by juan-ramirez-sp** [PagerDuty/terraform-provider-pagerduty#397]
### Terraform Version
0.14.7

### Provider Versions

1.9.5
1.11.0

### Affected Resource(s)
- pagerduty_ruleset_rule

### Terraform Configuration Files
```hcl
# This is a var 
rule_yaml_files    = fileset(path.module, "rules/**")

### Actual code
locals {

  rule_yaml_objects = flatten([for yaml_file in var.rule_yaml_files : yamldecode(file(yaml_file))])

  # Only get objects where rules isn't null. Then flatten to an array of rules.
  rules = flatten([for obj in local.rule_yaml_objects : obj.rules if obj.rules != null])

  # Get hashes of valid rules, by converting back to yaml.
  rule_hashes = [for rule in local.rules : sha256(yamlencode(rule))]

}

resource "pagerduty_ruleset_rule" "rules" {
  # Zip rule hash and rule object. The resource key is now the hash, making it resistant to shifting orders.
  for_each = zipmap(local.rule_hashes, local.rules)
  ruleset  = pagerduty_ruleset.ruleset.id
  # Pull the index key of the rulehash, this will correspond to the rule position.
  position = index(local.rule_hashes, each.key)
  disabled = each.value.disabled

  conditions {
    operator = each.value.conditions.operator

    dynamic "subconditions" {
      for_each = each.value.conditions.subconditions
      content {
        operator = subconditions.value.conditions.operator
        parameter {
          value = subconditions.value.conditions.parameter.value
          path  = subconditions.value.conditions.parameter.path

        }
      }
    }
  }

  actions {
    # Route doesn't like null, so let's exclude the block if the route is null.
    dynamic "route" {
      for_each = compact([each.value.actions.route])

      content {
        value = each.value.actions.route
      }
    }
    # This should never be null, either true or false.
    suppress {
      value = each.value.actions.suppress
    }

    # Severity doesn't like null, so let's exclude the block if the route is null.
    dynamic "severity" {
      for_each = compact([each.value.actions.severity])

      content {
        value = each.value.actions.severity
      }
    }

    # Can be empty string, a bug will constantly show drift if set to null or empty after being set initially.
    annotate {
      value = each.value.actions.annotate
    }
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The provider should apply all rules in order and have no drift once apply is complete.

### Actual Behavior
Terraform applies the rules in parallel and the provider/pagerduty doesn't provided consistent order of the rules.

Multiple applies must be done to ensure consistency for rule postions.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Create multiple rules under a directory in yaml format ( at least 10 )
2. `terraform apply`
3. Repeat step 2 until there are no changes.

### Important Factoids
We are dynamically creating rules from a yaml file and using a hash to recreate them for better consistency when changes occur.

Setting the parallelism to 1 just causes rules in the wrong position to error.

### References
N/A

**Comment by v0lumehi** [comment]
I experience the same issue

**Comment by NeishaS** [comment]
I am having the same problem. I have 13 rules.

**Comment by MB27472** [comment]
I believe, though have not verified, that this is due to parallelism (as inferred by @juan-ramirez-sp )

For a blank ruleset, if the configuration calls for rule position = 1, then 2, then 3, the 3rd rule may get created first (at position = 0) because rules 0, 1, and 2 do not yet exist. The API does not error on this case because creating a rule at position 0 was the only option and position 3 was impossible.

For creating rules in an existing ruleset, the same applies to a similar extent:
Rules 0 through 30 already exists and your configuration calls for new rules at position 28, 29, and 30. If the 3rd rule is created first, it will be placed at _current_ position 30. This now exists one location above the last rule (last rule now at position 31). When rule with location 28 is created, previously created rule now drops one position to position 31.

This is a very simple example but it illustrates the issue, which occurs exponentially for configs with many more rules. Each re-apply of the config attempts to correct this but risks re-arranging the positions incorrectly throughout the apply process. The only solution would be for Terraform to run serially from top to bottom, or to re-verify the applied configuration at the end of a run.

**Comment by mrwacky42** [comment]
Remember the game show _Name That Tune_? Of course you don't.
However, I can replicate with just 4 ruleset_rules.
I worry that, as is, every rule must [depend on](https://www.terraform.io/language/meta-arguments/depends_on) a prior rule, to explicitly order creation. Unfortunately, this is not very nice, dynamic or ergonomical.

```
│ Error: PUT API call to https://api.pagerduty.com/services/<REDACT>/rules/<REDACT> failed 404 Not Found. Code: 0, Errors: <nil>, Message: Rule Not Found
│
│   with module.pagerduty_service.pagerduty_service_event_rule.default["warning"],
│   on main.tf line 215, in resource "pagerduty_service_event_rule" "default":
│  215: resource "pagerduty_service_event_rule" "default" {
│
```

**Comment by bowenisdum** [comment]
I encountered the same issue, my current workaround is to use depends_on to chain the creation together explicitly, the order is reversed though, i.e. first rule is the last to be evaluated, not great

**Comment by bowenisdum** [comment]
if anyone else has this problem, a solution I was able to work with to get consistent behavior is to:
- create rules in order from first to evaluate to last, set position starting from 0, and only increment by 1
- if you have a catch_all rule, always put it last with position set correctly based on above ^ comment
- chain the rules together using `depends_on` to make sure they are created sequentially one after another.

**Comment by juan-ramirez-sp** [comment]
Rules are being deprecated and replaced
