### ISSUE TITLE
Travis-CI.org is shutdown, move to Github Actions?

### ISSUE THREAD

**Issue by pdecat** [PagerDuty/terraform-provider-pagerduty#403]
The CI for this project is no longer working, the last build job dating 4 months ago: https://travis-ci.org/github/PagerDuty/terraform-provider-pagerduty

This is caused by travis-ci.org shutdown:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

https://blog.travis-ci.com/2021-05-07-orgshutdown

@stmcallister Would you accept a PR switching from Travis CI to Github Actions?

It would provide better integration with Github UI IMO.

**Comment by stmcallister** [comment]
@pdecat are you referring to this? https://github.com/heimweh/go-pagerduty/pull/61
