### ISSUE TITLE
Operator is required in rule condition

### ISSUE THREAD

**Issue by idsvandermolen** [PagerDuty/terraform-provider-pagerduty#422]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/pagerduty/pagerduty v2.1.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_ruleset_rule

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "pagerduty_ruleset" "global-monitoring" {
  name = "Global Monitoring"
}

resource "pagerduty_ruleset_rule" "platform" {
  ruleset = pagerduty_ruleset.global-monitoring.id

  conditions {
    subconditions {
      operator = "equals"
      parameter {
        path  = "payload.notify"
        value = "platform"
      }
    }
  }

  actions {
    route {
      value = pagerduty_service.platform.id
    }
  }
}
```

Note we have a single `subconditions` block and the `operator` is missing at `conditions` level. The documentation mentions this about the `condition` block:
> operator - Operator to combine sub-conditions. Can be and or or.

No mention if this is required or not. Running `terraform init`, `terraform fmt`, `terraform validate` and `terraform plan` yields no warnings or errors.

### Expected Behavior
What should have happened?
The code should have been applied correctly or a warning/error should have been raised in earlier steps. Also the documentation should mention this is a required parameter. Alternatively make this `operator` optional.

### Actual Behavior
What actually happened?
When running `terraform apply` you get this error:
```
Error: POST API call to https://api.eu.pagerduty.com/rulesets/5a1384c0-c274-4273-8263-13ec169c8ab1/rules failed 400 Bad Request. Code: 0, Errors: map[conditions:map[operator:[can't be blank]]], Message: Invalid payload
```

Adding an `operator` condition like this fixed the `apply`:
```hcl
resource "pagerduty_ruleset" "global-monitoring" {
  name = "Global Monitoring"
}

resource "pagerduty_ruleset_rule" "platform" {
  ruleset = pagerduty_ruleset.global-monitoring.id

  conditions {
    operator = "and"
    subconditions {
      operator = "equals"
      parameter {
        path  = "payload.notify"
        value = "platform"
      }
    }
  }

  actions {
    route {
      value = pagerduty_service.platform.id
    }
  }
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
- no

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- no

**Comment by gsreynolds** [comment]
Rules are being deprecated and replaced
