### ISSUE TITLE
pagerduty_service_event_rule with count fails to create

### ISSUE THREAD

**Issue by spencer-langley** [PagerDuty/terraform-provider-pagerduty#426]
### Terraform Version
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.67.0
+ provider registry.terraform.io/pagerduty/pagerduty v2.1.1

### Affected Resource(s)
pagerduty_service_event_rule

### Terraform Configuration Files
```hcl
ui_managed_teams = {
  "system" = {
    team_name               = "Team"
    team_config_key_name    = "team"
    service_name            = "service"
    escalation_policy_name  = "test-ui-managed-team-policy"
    time_zone               = "America/New_York"
    dont_disturb_schedules = [
      {
        weekdays = [6, 7],
        start_time = 1632283200000,
        duration  = 86364000
      },
      {          
        weekdays = [1, 2, 3, 4, 5],
        start_time = 1632283200000,
        duration  = 32400000
      },
      {
        weekdays = [1, 2, 3, 4, 5],
        start_time = 1632340800000,
        duration  = 28800000
      }
    ]
  }
}

resource "pagerduty_service_event_rule" "mute_off_hour_notification" {
 count = length(var.ui_managed_teams.dont_disturb_schedules)
 service = pagerduty_service.service.id
 position = count.index
 disabled = false
 conditions {
     operator = "and"
     subconditions {
         operator = "contains"
         parameter {
             value = "restapi"
             path = "summary"
         }
     }
 }
 actions {
     suppress {
         value = true
     }
 }
 time_frame {
   scheduled_weekly {
     weekdays =  var.ui_managed_teams.dont_disturb_schedules[count.index].weekdays
     timezone = var.ui_managed_teams.time_zone
     start_time = var.ui_managed_teams.dont_disturb_schedules[count.index].start_time
     duration =  var.ui_managed_teams.dont_disturb_schedules[count.index].duration
   }
 }
}
```

### Expected Behavior
Create 3 pagerduty_service_event_rule resources

### Actual Behavior
Create 1 or 2 pagerduty_service_event_rule resources. Where only 1 is created, the event with position 1 creation fails with 404 (inspecting the state shows an id, but no rule exists) and the event with position 2 fails with error "Error updating service event rule [SOME UUID] position 1 needs to be 2"

If two are created, the rule with position 2 fails with the same 404 error above

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
create the resources described

### Important Factoids
Inspecting in the PagerDuty UI and Terraform state seems to show that the 2nd or 3rd resource in the count fails to be created, but the state has an id for a non existent rule. Additionally, sometimes a rule with a later position attempts creation before an earlier one (say, 2 before 1) and is rejected as invalid

**Comment by gsreynolds** [comment]
pagerduty_service_event_rule
