### ISSUE TITLE
Feature Request: Support for setting Remediate > Documentation Link via Terraform

### ISSUE THREAD

**Issue by jjm** [PagerDuty/terraform-provider-pagerduty#429]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/pagerduty/pagerduty v2.1.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_service

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
n/a

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

It should be possible to add a link to the Documentation for a service when creating service, as this is currnently only possible via the WebUI after the service has been created. 

A example setting up the service:

```terraform
resource "pagerduty_service" "this" {
  name                    = "example"
  documentation_link = "https://example.com/services/example"
  escalation_policy       = pagerduty_escalation_policy.example.id
  alert_creation          = "create_alerts_and_incidents"
}
```

### Actual Behavior
What actually happened?

n/a

### Steps to Reproduce
n/a Feature request.

### Important Factoids
This feature has been about around a year now, still missing an API.

### References
- https://community.pagerduty.com/forum/t/how-to-manage-a-services-remediate-documentation-link-via-the-api/1990

**Comment by stmcallister** [comment]
Thanks for the feedback! I agree this would be a great feature. It first needs to be made available through the PagerDuty API. I've created a feature request internally for the product development team at PagerDuty to consider adding this to the API. Once it's there, we can add it to the provider. 

Going to close. Please repost if you have any further context or questions.
