### ISSUE TITLE
Use the official go-pagerduty module

### ISSUE THREAD

**Issue by jensenbox** [PagerDuty/terraform-provider-pagerduty#430]
Looking through the source code it appears that there is significant use of personal github repository and not the official Pagerduty provided repository.

https://github.com/PagerDuty/terraform-provider-pagerduty/search?q=heimweh

The official documentation prescribes the corporate blessed repository here: https://github.com/PagerDuty/go-pagerduty#installation

While this is likely a fairly large undertaking, it should bolster confidence in using the provider in corporate environments.

**Comment by stmcallister** [comment]
Thanks for the feedback! And, you are exactly right! However, as you mentioned, it is a significant undertaking. The `heimweh` library was created by the creator of the provider and there wasn't an official `go-pagerduty` library at the time. It's a definite desire to incorporate the `PagerDuty/go-pagerduty` library, but with limited bandwidth other priorities have taken precedence...like keeping the provider consistent with the API. 😉

**Comment by stmcallister** [comment]
Going to close this as the request is on our radar.
