### ISSUE TITLE
"If none of the previous rules match" ignores "Suppress Alert" setting

### ISSUE THREAD

**Issue by mambax** [PagerDuty/terraform-provider-pagerduty#438]
### Terraform Version
```
❯ terraform -version
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/pagerduty/pagerduty v2.2.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_ruleset_rule

### Panic Output
none, logical error

### Actual Behavior
![image](https://user-images.githubusercontent.com/5472171/147220078-1c133bc8-3d89-4d51-bd15-3b9e485e9315.png)
It does not matter what is selected in that radio button, this seems to be not reflected in terraform.

### Steps to Reproduce
Setup a ruleset and some ruleset_rules and toggle it, the code and terraform plan don't mind it 😄 I am not sure if it even matters in the UI the fact is though that its inconsistent with the terraform resources and state.

### Important factoids
This is the catchall rule (the last without conditions).

**Comment by gsreynolds** [comment]
Rules are being deprecated and replaced
