### ISSUE TITLE
Unable to set "No Priority" vs "Any Priority" for priorities in pagerduty_slack_connection

### ISSUE THREAD

**Issue by PitcherIT** [PagerDuty/terraform-provider-pagerduty#456]
Hi there,

It seems through the provider I am unable to set the priority on a slack connection to the “No priority” option (not “Any priority” option).  Through the REST API directly you can set/return this via `priorities: []` (for "No priority"), versus `priorities: null` (for "Any priority").
With Terraform I have tried omitting the priorities value, using `priorities = []`, `priorities = null` and `priorities = tolist([])` but this actually sets it to the "Any priorities" option.

### Terraform Version
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/pagerduty/pagerduty v2.2.1

### Affected Resource(s)
pagerduty_slack_connection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
If setting `priorities = []` it should set the Priorities option to "No priority"
If setting `priorities = null` or omitting, it should set the Priorities option to "Any priority"
If setting `priorities = []` and resource exists and is set to "Any priority", it should see there is a change required, and apply changes it to "No priority".

### Actual Behavior
If setting `priorities = []` it sets the Priorities option to "Any priority"
If setting `priorities = []` and resource exists and is set to "Any priority", it see's there is no change to make

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
-

### References
-

**Comment by imjaroiswebdev** [comment]
Hi there @PitcherIT 👋🏽 We addressed this Issue in the release [v2.5.1](https://github.com/PagerDuty/terraform-provider-pagerduty/releases/tag/v2.5.1). Try to give a look at the [updated documentation](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/slack_connection) for the new considerations to take in count.
