### ISSUE TITLE
Add support for email_parsers and email_filters

### ISSUE THREAD

**Issue by braun1928** [PagerDuty/terraform-provider-pagerduty#459]
I've been working in a PR to extend `pagerduty_service_integration` and support the email filters and parsers. I pushed it recently, incomplete, and then I saw there is a draft PR (#163) from 2019 that implements it, basically the same way.

The PR is stale for long, has conflicts, so it needs to be updated; I can continue working on my branch, adding the remaining things (documentation, tests, etc) if that is easier.

**Comment by stmcallister** [comment]
Thanks for opening this issue! You are right, #163 was stale so I created #468 with most of that code. This was merged and went out with v2.4.0 of the provider. 

Going to close this issue. Please reopen if there are any further questions or issues.
