### ISSUE TITLE
ruleset_rule for catch-all rule cannot be set up according to documentation 

### ISSUE THREAD

**Issue by andreas-lundgren-storytel** [PagerDuty/terraform-provider-pagerduty#463]
### Terraform Version
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.10.0
+ provider registry.terraform.io/pagerduty/pagerduty v2.2.1

### Affected Resource(s)
- pagerduty_ruleset_rule

### Terraform Configuration Files
```hcl
resource "pagerduty_ruleset_rule" "catch-all-defualt" {
  ruleset  = pagerduty_ruleset.stackdriver.id
  conditions {
  }
  actions {
    route {
      value = pagerduty_service.storytel-platform-high-urgency.id
    }
    severity {
      value = "critical"
    }
    annotate {
      value = "Managed by Terraform - do not edit"
    }
  }
}

```

### Debug Output
I cannot provide to full debug output, it contained too much personal stuff and I saw our PAgerDuty token in there. It was just too large for me to walk through and sanitise. But I think the panic output below is enough, it's very easy to reproduce:

### Panic Output
https://gist.github.com/andreas-lundgren-storytel/cf442117bfa5bf123e16b27cd8a1a87a

In essense: Conditions clause is empty: ` interface conversion: interface {} is nil, not map[string]interface {}`

### Expected Behavior
documentation states that 
[conditions](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/ruleset_rule#conditions) - (Required) Conditions evaluated to check if an event matches this event rule. *Is always empty for the catch-all rule, though.*

### Actual Behavior
he terraform-provider-pagerduty_v2.2.1 plugin crashed!

### Steps to Reproduce
1. `terraform apply -target pagerduty_ruleset_rule.catch-all`

**Comment by speedfl** [comment]
Same apply for the version 2.4.0. 

This is a serious issue. As the plugin crash, you are in an inconsistent state making it impossible to do a terraform destroy afterward if you have several resources

**Comment by speedfl** [comment]
Looking at the code it appears that conditions is marked as Optional

https://github.com/PagerDuty/terraform-provider-pagerduty/blob/master/pagerduty/resource_pagerduty_ruleset_rule.go#L39

I tried by removing it but got following error when doing POST call to https://api.pagerduty.com/ruleset/123456/rules

```
map[conditions:[can't be blank]] 
```
A solution could be to let it Optional, update the doc and create an empty structure is not present. I will try to submit a PR

**Comment by speedfl** [comment]
I think we can close this issue @stmcallister . Do you know when it will be released and available in Terraform registry

**Comment by stmcallister** [comment]
Thanks for your work on this @speedfl ! Your PR went out with [v2.4.2](https://github.com/PagerDuty/terraform-provider-pagerduty/releases/tag/v2.4.2)! Closing issue.
