### ISSUE TITLE
Add support for event_orchestrations API

### ISSUE THREAD

**Issue by porkcharsui** [PagerDuty/terraform-provider-pagerduty#465]
Please add support for the newly released Events Orchestration API 

Docs: https://support.pagerduty.com/docs/event-orchestration

Sample API: https://developer.pagerduty.com/api-reference/b3A6MzU3MDU0Mzc-create-an-orchestration

**Comment by jussisallinen** [comment]
This would be really great addition to the Terraform provider - we only solely deal with Event Orchestration (aka Global Orchestrations).

**Comment by brenwhyte** [comment]
+1 Would love to see this too and will likey wait for this to be a reality before migrating.

**Comment by viktor-f3** [comment]
Definitely need this feature to be supported by terraform provider. Creating this manually or via REST API is not an option for us.

**Comment by stmcallister** [comment]
There is an engineering team at PagerDuty who is working on adding Event Orchestration to the provider as we speak. I don't have an external timeline, but wanted to share that it's in development.

**Comment by jussisallinen** [comment]
@stmcallister Any update on this one? Beta available to test? :)

**Comment by pzhuravlenkopd** [comment]
this has now been released: https://github.com/PagerDuty/terraform-provider-pagerduty/blob/v2.5.0/CHANGELOG.md#250-june-1-2022

**Comment by porkcharsui** [comment]
Thanks for the update @pzhuravlenkopd. I'm closing this issue as resolved as of v2.5.0
