### ISSUE TITLE
Inconsistent Terraform <> PagerDuty API Behaviour

### ISSUE THREAD

**Issue by marceloboeira** [PagerDuty/terraform-provider-pagerduty#469]
We have been facing inconsistent terraform and/or pagerduty API behavior while using the provider with service_event_rules.

Sometimes plan/apply works smoothly, other times, for the same code, it plans correctly but when applying it errors after creating the resources with  a 404.

We have a module that creates event rules for a specific service:
 
```terraform
module "service_x_event_router" {
  source     = "modules/pagerduty/event_router"
  service_id = module.service_x.id
}
```

The module is simply creating rules to manage priority/urgency based on tags from events:
```terraform
## Priority
data "pagerduty_priority" "p5" {
  name = "P5"
}

resource "pagerduty_service_event_rule" "example" {
# this comes from the module variables  
service  = var.service_id
  position = 1

  conditions {
    operator = "and"

    subconditions {
      operator = "contains"
      parameter {
        value = "urgency:low"
        path  = "custom_details.tags"
      }
    }
  }

  actions {
    severity {
      value = "info"
    }
    priority {
      value = data.pagerduty_priority.p5.id
    }
    annotate {
      value = "Low priority tag detected this alert is lowered to P5."
    }
  }
}

...
```

### Terraform Version
```
Terraform v1.0.10
on darwin_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_service_event_rule

### Expected Behavior

Resources created

### Actual Behavior

Errors
These are the two errors we frequently see: 
* Rule not Found (right after it created with apply)
* Position needs x to be y - Usually happens when 1 rule apparently fails to create

The important bit to remember: running plan/apply again works... somehow. This doesn't fail consistency.
 
```
│ Error: GET API call to https://api.pagerduty.com/services/_REDACTED__/rules/_REDACTED__ failed 404 Not Found. Code: 0, Errors: <nil>, Message: Rule Not Found
│ 
│   with module.esro_event_router.pagerduty_service_event_rule.low_urgency_alert,
│   on ../../../modules/pagerduty/event_router/main.tf line 45, in resource "pagerduty_service_event_rule" "low_urgency_alert":
│   45: resource "pagerduty_service_event_rule" "low_urgency_alert" {
│ 
╵
╷
│ Error: Error updating service event rule _REDACTED__ position 3 needs to be 4
│ 
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
3. `terraform apply`

**Comment by gsreynolds** [comment]
Rules are being deprecated and replaced
