### ISSUE TITLE
Documentation improvement - Slack connection resource

### ISSUE THREAD

**Issue by katkasian** [PagerDuty/terraform-provider-pagerduty#492]
It could be beneficial to mention that `pagerduty_slack_connection` resource only works with Slack Next Gen, and not v2. https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/slack_connection

**Comment by imjaroiswebdev** [comment]
@katkasian Thanks for pointing out this. I'm going close it, because it has been addressed in #496.
