### ISSUE TITLE
No Catch-all rule found. Catch-all Resource must exists error when having large number (40) of ruleset rules then trying to update catch_all rule.

### ISSUE THREAD

**Issue by mjdatarioavaloq** [PagerDuty/terraform-provider-pagerduty#540]
Hi, creating pagerduty_ruleset_rule with catch_all true prompts an error when there's currently a large number of ruleset rules. maybe above pagination limit of [client.Rulesets.ListRules(rule.Ruleset.ID)](https://github.com/PagerDuty/terraform-provider-pagerduty/pull/481/files#diff-4d4163e3d7724502bf1de1d3dfb3287abaffc2866b570428fecf1f4e61c3fe09R766)

### Terraform Version
Terraform v1.2.3
on windows_amd64

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_ruleset_rule

### Terraform Configuration Files
```hcl
resource "pagerduty_ruleset_rule" "catch_all" {
  ruleset   = var.pagerduty_ruleset_id
  catch_all = true

  actions {
    route {
      value = pagerduty_service.self.id
    }
    severity {
      value = "info"
    }
    priority {
      value = data.pagerduty_priority.p5.id
    }
    annotate {
      value = "Uncategorized Event to be analysed and properly mapped as an event rule."
    }
  }
}
```

### Expected Behavior
Ruleset rule should be created regardless of the number of current ruleset rule implemented

### Actual Behavior
An error was returned: Error: No Catch-all rule found. Catch-all Resource must exists

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Implement a multiple ruleset rules with more than the pagination limit of `client.Rulesets.ListRules(rule.Ruleset.ID)`
2. Add a pagerduty_ruleset_rule with catch_all set to true
3. Run terraform apply

### References
- https://github.com/PagerDuty/terraform-provider-pagerduty/pull/481/files#diff-4d4163e3d7724502bf1de1d3dfb3287abaffc2866b570428fecf1f4e61c3fe09R785

**Comment by shybbko** [comment]
Observing this as well with the latest provider: 

```
# terraform -version
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.59.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/pagerduty/pagerduty v2.11.2

Your version of Terraform is out of date! The latest version
is 1.4.2. You can update by downloading from https://www.terraform.io/downloads.html
```

The limit is somewhere between 17 rules (working fine) and 65 rules (seeing error).

**Comment by gsreynolds** [comment]
Rules are being deprecated and replaced
