### ISSUE TITLE
API call failed: 429 Too Many Requests

### ISSUE THREAD

**Issue by FelixBarsnickTS** [PagerDuty/terraform-provider-pagerduty#546]
Hi there,

in our CI we run the Terraform apply in parallel for all our Pagerduty services. This was ok, but with the number of services growing (now around 80) we are running into a API rate limit problem.

### Terraform Version
1.1.x

### Error Output
│ Error: GET API call to https://api.pagerduty.com/abilities failed: 429 Too Many Requests
│ 
│ 
│ No valid credentials found for PagerDuty provider.
│ Please see https://www.terraform.io/docs/providers/pagerduty/index.html
│ for more information on providing credentials for this provider.
│ 
│ 
│   with module.this.pagerduty_escalation_policy.this[0],
│   on .terraform/modules/this/escalation-policy.tf line 1, in resource "pagerduty_escalation_policy" "this":
│    1: resource "pagerduty_escalation_policy" "this" {

### Expected Behavior
I'd expect the provider to take care of API rate limits itself.

### Actual Behavior
Most of the CI step is processed but a handful fails with the error message mentioned.

### Steps to Reproduce
Set up a large number of services in TF with each in a separate TF state. Then let the TF plan and apply in a CI with every service in parallel.

### Important Factoids
We use CircleCI as CI tool.

Thanks for your help
Felix

**Comment by frek818** [comment]
@FelixBarsnickTS , tid you do something to work around this or did some external factor relieve you of the issue?
