### ISSUE TITLE
[Feature Request]  - auto_pause_notifications_parameters

### ISSUE THREAD

**Issue by BillSidney** [PagerDuty/terraform-provider-pagerduty#547]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
% terraform -v
Terraform v1.2.3
on darwin_amd64
```

### Affected Resource(s)
- pagerduty_service

### Why

I want to enable `Auto-Pause Incident Notifications` for the service created with Terraform to reduce noise.

**Comment by pdecat** [comment]
https://github.com/PagerDuty/terraform-provider-pagerduty/pull/525

**Comment by BillSidney** [comment]
Thank You - this resolves my issues

**Comment by elihai-risk** [comment]
This Feature  doesn't apply by Terraform
in the Terraform plan it show it is going to add it but in the UI it's still off.
if i changing manually it doesn't show me drift

**Comment by pdecat** [comment]
Hi @elihai-risk, would you mind opening a new issue including details about your terraform version, terraform Pagerduty provider version, terraform configuration files, and debug logs with the `TF_LOG=debug` environment variable set (*redact any confidential information from that log*).
