### ISSUE TITLE
Add support for Licenses in User resources

### ISSUE THREAD

**Issue by gsreynolds** [PagerDuty/terraform-provider-pagerduty#631]
https://developer.pagerduty.com/api-reference/4cb4fd0f5444a-create-a-user - `license` field is newly added

Will likely also need a data source for available licenses types: https://developer.pagerduty.com/api-reference/4c10cb38f7381-list-licenses

Something like:
```terraform
data "pagerduty_license" "digital_operations_full" {
  name = "Digital Operations (Full User)"
}

resource "pagerduty_user" "example" {
  name  = "Earline Greenholt"
  email = "125.greenholt.earline@graham.name"
  license = data.pagerduty_license.digital_operations_full.id
}
```

**Comment by imjaroiswebdev** [comment]
Hey @gsreynolds support for License Data source and management of user license have been released on [v2.14.0](https://github.com/PagerDuty/terraform-provider-pagerduty/releases/tag/v2.14.0). Thank you for bringing the attention to this 💪🏽 😎
