### ISSUE TITLE
GitHub Integration (`pagerduty_service_integration`)  isn't working properly - does not display change events

### ISSUE THREAD

**Issue by Daniel-Vaz** [PagerDuty/terraform-provider-pagerduty#634]
# Issue

When creating a GitHub integration using the `pagerduty_service_integration` resource. The integration appears correctly on the UI, and I can even send webhooks without errors to it, but nothing is displayed under **Recent Changes** Section of the Pagerduty Service.

In Pagerduty UI I see:
![image](https://user-images.githubusercontent.com/29305556/219449593-22d200d6-efea-4595-a749-e4c5e8c42c6f.png)

In Github I can confirm the Webhooks are being sent correctly:
![image](https://user-images.githubusercontent.com/29305556/219449846-85b80658-d3ef-4a45-a48d-4ba9e8377fe3.png)

![image](https://user-images.githubusercontent.com/29305556/219449771-d1fcd9b9-feaf-4f7e-af73-86ca423f5558.png)

But nothing appears in the Change Events section:
![image](https://user-images.githubusercontent.com/29305556/219449995-406fce4b-316a-4e73-a1f7-46419d3793dd.png)

I tried creating this integration manually and it works as expected:
![image](https://user-images.githubusercontent.com/29305556/219450188-d2f9978e-6972-4753-91ee-5672b50aa565.png)

It simply does not work when I do it using Terraform.

### Terraform Version
```sh
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.17.0
+ provider registry.terraform.io/pagerduty/pagerduty v2.11.0
```

### Affected Resource(s)
- pagerduty_service_integration

### Terraform Configuration Files
```hcl
data "pagerduty_vendor" "github" {
  name = "Github"
}

resource "pagerduty_service_integration" "github_k8s_catchall" {
  name    = data.pagerduty_vendor.github.name
  service = pagerduty_service.my_service.id
  vendor  = data.pagerduty_vendor.github.id
}
```

### Expected Behavior
PRs appear properly on the Pagerduty Services Page UI.

### Actual Behavior
Nothing appears there:
![image](https://user-images.githubusercontent.com/29305556/219448953-9f3b0355-f21d-4d70-a7d5-360536c2893d.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create the resources as shown above;
2.  Apply the code;
3. In github create a webhook configuration
4. Open a PR and see if something appears on the Services Page UI of Pagerduty;

**Comment by DoctorPolski** [comment]
After you have created a working integration on the PagerDuty console you could import it into your Terraform resource and plan it to what, if any, differences there might be.

Of course you will need to remove the existing state for your resource if it is in place.

**Comment by Daniel-Vaz** [comment]
@DoctorPolski 
Thank you for the answer but indeed it was just a stupid mistake on my side. 

To create the Webhook on GitHub I blindly  followed [this](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/service_integration#:~:text=To%20configure%20an%20event%2C%20please%20use%20the%20integration_key%20in%20the%20following%20interpolation%3A) reference in the docs.

This resulted on my webhook endpoint to just end in `/enqueue` instead of the correct `/change/enqueue`.
After I fixed this it all went smoothly as expected. 

Thank you anyway for your time 😄 !
