### ISSUE TITLE
Failed to create pagerduty_event_orchestration_service with trigger_count

### ISSUE THREAD

**Issue by TuChunYen** [PagerDuty/terraform-provider-pagerduty#662]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v1.0.3

### Affected Resource(s)
- pagerduty_event_orchestration_service

### Terraform Configuration Files
```hcl
resource "pagerduty_event_orchestration_service" "test" {
  service                                = pagerduty_service.test.id
  enable_event_orchestration_for_service = true
   set {
    id = "second"
    rule {
      actions {
        event_action = "trigger"
        priority     = data.pagerduty_priority.p1.id
        severity     = "critical"
        route_to     = "third"
      }
      condition {
        expression = "not event.custom_details.NewStateValue matches 'OK'"
      }
    }
    rule {
      actions {
        event_action = "resolve"
        priority     = data.pagerduty_priority.p1.id
        severity     = "critical"
      }
      condition {
        expression = "event.custom_details.NewStateValue matches 'OK'"
      }
    }
  }
  set {
    id = "third"
    rule {
      actions {
        suppress = true
      }
      condition {
        expression = "trigger_count over 45 minuter >> 3"
      }
    }
  }
  catch_all {
    actions {}
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Successfully create service orchestration

### Actual Behavior
Terraform apply failed with 
```bash
 Error: PUT API call to https://api.pagerduty.com/event_orchestrations/services/P40SFPJ failed 400 Bad Request. Code: 0, Errors: map[sets:[map[] map[] map[rules:[map[conditions:[map[expression:[Expected boolean expression but found identifier '"trigger_count"' at line 1 offset 0]]]]]]]], Message: Invalid payload
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by metavida** [comment]
While the error message returned from the API is very confusing, it is indicating that there's error with the [PCL](https://developer.pagerduty.com/docs/ZG9jOjM1NTE0MDc0-pager-duty-condition-language-pcl#threshold-conditions) expression that you've specified. Looking at your code sample I see two problems with the condition.expression in the rule in the "third" set:

1. Time unit should be `minutes` instead of `minuter`
2. Comparison should be `>` instead of `>>`

If you make the following change to the rule the Terraform should apply cleanly:

```diff
  set {
    id = "third"
    rule {
      actions {
        suppress = true
      }
      condition {
+        expression = "trigger_count over 45 minutes > 3"
-        expression = "trigger_count over 45 minuter >> 3"
      }
    }
  }
```

Let us know if this suggestion doesn't resolve your issue!
