### ISSUE TITLE
alert_grouping_parameters: Plan not recognizing applied changes 

### ISSUE THREAD

**Issue by roreid** [PagerDuty/terraform-provider-pagerduty#700]
### Terraform Version
terraform -v
Terraform v1.3.1
on windows_amd64
+ provider registry.terraform.io/pagerduty/pagerduty v2.15.0

### Affected Resource(s)
- pagerduty_service resource

### Terraform Configuration Files
```hcl
data "pagerduty_user" "user" {
  email = "youruser@yourdomain.com"
}

resource "pagerduty_escalation_policy" "foo" {
  name      = "Engineering Escalation Policy"
  num_loops = 2

  rule {
    escalation_delay_in_minutes = 10

    target {
      type = "user_reference"
      id   = data.pagerduty_user.user.id
    }
  }
}

# PagerDuty service - No config{} block
resource "pagerduty_service" "service_no_config_block" {
  name = "No Config Block"

  escalation_policy = pagerduty_escalation_policy.foo.id

  auto_resolve_timeout    = "null"
  acknowledgement_timeout = 3600
  alert_creation          = "create_alerts_and_incidents"

  alert_grouping_parameters {
    type = "intelligent"
  }
}

# PagerDuty service - With config{} block
resource "pagerduty_service" "service_with_config_block" {
  name = "With Config Block"

  escalation_policy = pagerduty_escalation_policy.foo.id

  auto_resolve_timeout    = "null"
  acknowledgement_timeout = 3600
  alert_creation          = "create_alerts_and_incidents"

  alert_grouping_parameters {
    type = null
    config {}
  }
}

```

### Debug Output
https://gist.github.com/roreid/a9e31f1070e50db9b89a750d81e2a43b

### Expected Behavior
The Plan should be '0 to change' after the initial `terraform apply` has been performed

### Actual Behavior
After the initial `terraform apply`, the Plan still says '2 to change' when another `terraform plan` is run

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Replace the user email address in `pagerduty_user` resource with one from your PagerDuty instance
2. Run `terraform apply` - the Plan will report '2 to change'
3. Run `terraform apply` again - the Plan will still report '2 to change'. Successive applies will report the same.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #520
- #550

**Comment by benlangfeld** [comment]
It looks like specifying the following is a useful workaround:

```
    config {
      fields  = null
      timeout = null
    }
```

Unfortunately #617 remains a problem.
