### ISSUE TITLE
Error: GET API call to https://api.pagerduty.com/abilities failed because abilities.read API 

### ISSUE THREAD

**Issue by headincl0ud** [PagerDuty/terraform-provider-pagerduty#757]
### Terraform Version
```1.5.2```

### Pagerduty Provider Version
```
  required_providers {
    pagerduty = {
      source  = "PagerDuty/pagerduty"
      version = "3.0.2"
    }
```

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_team
- pagerduty_user

### Terraform Configuration Files
```hcl
provider "pagerduty" {
  # Configure use of App Oauth scoped token
  use_app_oauth_scoped_token {
    pd_client_id     = var.pagerduty_client_id
    pd_client_secret = var.pagerduty_client_secret
    pd_subdomain     = var.pagerduty_subdomain
  }


  resource "pagerduty_user" "user" {
    email    = "test@gmail.com"
    name     = "Rob Test"
    role     = "user"
  
    lifecycle {
      ignore_changes = [role, job_title]
    }
  }
}
```

### Debug Output
Please provide a link to a GitHub Gist containing the complete debug output: 

```
│ Error: GET API call to https://api.pagerduty.com/abilities failed because abilities.read API scope is required
│ 
│ 
│ No valid credentials found for PagerDuty provider.
│ Please see https://www.terraform.io/docs/providers/pagerduty/index.html
│ for more information on providing credentials for this provider.
│ 
```

### Actual Behavior
Pagerduty is responding with an API error, although the scope is on the list. 
![image](https://github.com/PagerDuty/terraform-provider-pagerduty/assets/88448147/94a32c64-0170-4865-9d37-6ba9a764ee0e)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a new APP integration -> New App -> custom name & description 
2. Select OAuth 2.0 & Events Integration
3. Scoped OAuth -> select all for test purposes
4. Configure provider to use Oauth -> https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs#example-using-app-oauth-scoped-token
5. Configure `pagerduty_user` resource
6. `terraform init` & `terraform plan`

**Comment by gunzy83** [comment]
How did you end up resolving this? I just ran into this issue and everything seems to work fine if you set `skip_credentials_validation` but that is less than optimal.

**Comment by rlees85** [comment]
`use_app_oauth_scoped_token` just seems totally broken for me. Just errors out immediately with 403 running it normally and with `skip_credentials_validation` it just keeps trying the data source/resource over and over again but with a malformed `Authorization` header.

```
---[ REQUEST ]---------------------------------------
GET /users?query=me%40me.me HTTP/1.1
Host: api.eu.pagerduty.com
User-Agent: (linux amd64) Terraform/1.6.4
Accept: application/vnd.pagerduty+json;version=2
Authorization: Bearer
Content-Type: application/json
Accept-Encoding: gzip
```
