### ISSUE TITLE
documentation pagerduty_service_integration integration_key attribute is deprecated

### ISSUE THREAD

**Issue by Marcus-James-Adams** [PagerDuty/terraform-provider-pagerduty#782]
Hello
#775 introduced the deprecation  notice when running terraform plan & apply

The documentation https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/service_integration states that the attribute has been deprecated, however there is nothing to say what we would be using in it place

eg in the code block below what should we use for the servce_key field?

```
resource "pagerduty_service_integration" "myapp" {
  name    = "my-app-intergration"
  service = pagerduty_service.myapp.id
  vendor  = data.pagerduty_vendor.datadog.id
}

resource "datadog_integration_pagerduty_service_object" "myapp" {
  service_name = pagerduty_service.myapp.name
  service_key  = pagerduty_service_integration.myapp.integration_key
}
```

**Comment by vperaltac** [comment]
The deprecation warning also shows up when using `integration_key` as an output. There is already a PR pending that fixed this issue. Is there an ETA for the fix to be live?

**Comment by imjaroiswebdev** [comment]
This was addressed by https://github.com/PagerDuty/terraform-provider-pagerduty/pull/801. I'd suggest you to upgrade your current PagerDuty TF provider version to **v3.4.1**.
