### ISSUE TITLE
Unable to define time_window values > 1h

### ISSUE THREAD

**Issue by JelleSmet-TomTom** [PagerDuty/terraform-provider-pagerduty#849]
Hi there,

### Terraform Version
All versions. This is a provider error.

### Affected Resource(s)
- pagerduty_service

### Terraform Configuration Files
```hcl
resource "pagerduty_service" "service" {
  name                    = "Demo"
  description             = "Description"
  escalation_policy       = "abc"
  alert_creation          = "create_alerts_and_incidents"
  auto_resolve_timeout    = "null"
  acknowledgement_timeout = "null"
  alert_grouping_parameters {
    type = "content_based"
    config {
      aggregate   = "any"
      fields      = ["custom_details.business_service"]
      time_window = "86400"
    }
  }
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
The validation happening [here should](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/bf0e960b70d58c6e27aabf006a528b04c518fd58/pagerduty/resource_pagerduty_service.go#L365) also allow for value `86400`.
The PD api documentation does not mention this. 
The UI allows this (important) value to be set:

![image](https://github.com/PagerDuty/terraform-provider-pagerduty/assets/78075264/9f390014-aa9a-4a89-8963-248e4cdeccf6)

When setting this value through the UI and then doing a GET on the service resource we can see the value to be `86400`:

```
... snip ...
    "alert_grouping_parameters": {
      "type": "content_based",
      "config": {
        "fields": [
          "custom_details.some_field"
        ],
        "aggregate": "any",
        "time_window": 86400,
        "recommended_time_window": 300
      }
    },
... snip ...
```

### Actual Behavior
- providing `86400` as a value is refused by the Pagerduty provider through[ value validation.](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/bf0e960b70d58c6e27aabf006a528b04c518fd58/pagerduty/resource_pagerduty_service.go#L365)

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
n/a

### References
n/a

**Comment by imjaroiswebdev** [comment]
Hi @JelleSmet-TomTom, this is the expected functionality from our [API](https://developer.pagerduty.com/api-reference/7062f2631b397-create-a-service#request-body), due the officially supported value for the setting `pagerduty_service.alert_grouping_parameters.0.config.0.time_window` through our REST API is `>= 300 and <= 3600`.

![Screenshot 2024-05-29 at 2 47 12 PM](https://github.com/PagerDuty/terraform-provider-pagerduty/assets/24704624/36143dc5-dc80-4e24-99d9-a60a3e69c330)

Therefore, being that the PagerDuty Terraform provider is an interface to interact with our REST APIs, then the `time_window` attribute accepts the supported input range.

**Comment by imjaroiswebdev** [comment]
I'm reopening this issue because of https://github.com/PagerDuty/terraform-provider-pagerduty/pull/876#issuecomment-2168257348.
