### ISSUE TITLE
API calls cancelled by client because of Timeout

### ISSUE THREAD

**Issue by imjaroiswebdev** [PagerDuty/terraform-provider-pagerduty#899]
### Terraform Version

```sh
Terraform v1.6.6
on darwin_arm64
+ provider registry.terraform.io/pagerduty/pagerduty v3.14.4
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `pagerduty_schedule`
- This issue could not be limited to this specific resource.

### Debug Output
```sh
Error: Put https://api.pagerduty.com/schedules/P1TXG23: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

│

│   with module.teams.pagerduty_schedule.all["RIG MRC Team Rota"],

│   on .terraform/modules/teams/modules/teams/main.tf line 30, in resource "pagerduty_schedule" "all":

│   30: resource "pagerduty_schedule" "all" {
```

### Expected Behavior
Schedule/Resource should be updated

### Actual Behavior
Error while updating Schedule/Resource

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by whyisjacob** [comment]
@imjaroiswebdev,

we are using 3.14.5 and are running into this issue, what are the steps to resolve it?

**Comment by jcpoconnor** [comment]
Fyi - We had to pin to Version `3.14.4` to get our (admittedly rather large) plan to apply.
