### ISSUE TITLE
pagerduty_vendor for "Events API v2"

### ISSUE THREAD

**Issue by pedrocarrico** [PagerDuty/terraform-provider-pagerduty#932]
Hi,

I'm trying to get the details of  a PagerDuty vendor to create a service integration but when I fetch with the name "Events API v2" I get the details for "PRTG Notification For PagerDuty Events API v2".
The "Events API v2" integration is done by PageDuty not an external vendor so probably that integration isn't possible to be fetched from this API?
How can I fetch via terraform the details for this integration type so I can create a service integration correctly?

### Terraform Version
v1.8.5

### Affected Resource(s)
pagerduty_vendor on version 3.15.6

### Terraform Configuration Files
```hcl
data "pagerduty_vendor" "events_api_v2" {
  name = "Events API v2"
}

resource "pagerduty_service_integration" "example" {
  name    = data.pagerduty_vendor.events_api_v2.name
  service = pagerduty_service.example.id
  vendor  = data.pagerduty_vendor.events_api_v2.id
}
```

### Expected Behavior
On that data resource I should get the "Events API v2" vendor and integration details.

### Actual Behavior
I got the "PRTG Notification For PagerDuty Events API v2" vendor and integration details.

### Steps to Reproduce
Use the data resource, see that if fetches the wrong vendor for the integration.

### Important Factoids
- N/A

### References
- https://developer.pagerduty.com/api-reference/YXBpOjI3NDgyNjU-pager-duty-v2-events-api

**Comment by cavila-evoliq** [comment]
I don't think you can set that integration that way. They have some examples on how to fetch this in their docs [here](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/service_integration).

```hcl
resource "pagerduty_service_integration" "apiv2" {
  name            = "API V2"
  type            = "events_api_v2_inbound_integration"
  service         = pagerduty_service.example.id
}
```

The above should create a pagerduty service which you should be able to output with something like:

```hcl
output "integration_key" {
  description = "The integration key for the PagerDuty service."
  value       = sensitive(pagerduty_service_integration.apiv2.integration_key)
  sensitive   = true
}
```

**Comment by pedrocarrico** [comment]
Thanks @cavila-evoliq!
Yeah that seems to work well!
